version: "1"
rules:                      # Array of rules
  - base: master            # Required. Target branch
    upstream: jeffpiazza/derbynet    # Required. Must be in the same fork network.
    mergeMethod: merge  # Optional, one of [none, merge, squash, rebase, hardreset], Default: none  
label: ":arrow_heading_down: pull"  # Optional
conflictLabel: "merge-conflict"     # Optional, on merge conflict assign a custom label, Default: merge-conflict
