name: Build and Push Docker Images
on: [push]
jobs:
  Build-Docker-Dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4      
      
      - name: Create Quick Reference PDF
        uses: jmservera/libreoffice-action@v0.2
        with:
          command: libreoffice --headless --invisible --convert-to pdf 'docs/Quick Reference.fodt' --outdir 'website'
      
      - name: Rename the PDF
        run: mv website/Quick\ Reference.pdf website/quickref.pdf
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Build dependencies with Ant
        run: ant -noinput -buildfile build.xml banner generated-version.inc generated-build-date.inc release-series generated-commit-hash.inc webrtc-adapter      
      
      - name: List files in the website directory
        run: |
          ls ${{ github.workspace }}/website
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.CONTAINER_REG_USER }}
          password: ${{ secrets.CONTAINER_REG_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: installer/docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8
          push: true
          tags: landonc/derbynet_server:latest
